%%{ init: { "theme": "default", "themeVariables": { "background": "transparent" } } }%%

sequenceDiagram

    participant SharingUser as Sharing User
    participant SharingApp as SHL Sharing Application
    participant ReceivingApp as SHL Receiving Application
    participant ReceivingUser as Receiving User

    SharingUser ->> SharingApp: Create SHL { passcode }
    SharingApp -->> SharingUser: shlink:/ ...

    SharingUser -->> ReceivingUser: Sharing user exchanges SHL with receiving user

    ReceivingUser ->> ReceivingApp: View SHL #shlink:/ ...
    ReceivingApp ->> SharingApp: POST manifest-url { recipient, passcode }
    SharingApp -->> ReceivingApp: Manifest { files: [ { contentType, location | embedded } ]}

    alt 
        ReceivingApp ->> SharingApp: GET location
        SharingApp -->> ReceivingApp: encrypted(Bundle { type: 'document' })
    else
        ReceivingApp ->> ReceivingApp: Decode embedded content
    end

    ReceivingApp ->> ReceivingApp: Decrypt (SHL key)


   