%%{ init: { "theme": "default", "themeVariables": { "background": "transparent" } } }%%

sequenceDiagram
    participant Server as Patient Summary Server
    participant Consumer as Patient Summary Consumer

    Consumer->>Server: DocumentReference/$docref { ... }
    Server-->>Consumer: Bundle { type: 'searchset', entry[]: DocumentReference }

    Consumer->>Server: Bundle/[id] read
    Server-->>Consumer: Bundle { type: 'document' }